#!/bin/bash
#######################################################################
##- @Copyright (C) Huawei Technologies., Ltd. 2019. All rights reserved.
# - lcr licensed under the Mulan PSL v2.
# - You can use this software according to the terms and conditions of the Mulan PSL v2.
# - You may obtain a copy of Mulan PSL v2 at:
# -     http://license.coscl.org.cn/MulanPSL2
# - THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# - IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# - PURPOSE.
# - See the Mulan PSL v2 for more details.
##- @Description: apply patchs
##- @Author: lifeng
##- @Create: 2019-04-25
#######################################################################

set -ex

dir_name=$(tar -tzf *.tar.gz | head -1 | cut -f1 -d"/")
if [ -e $dir_name ]; then
    echo "directory $dir_name exist, please remove it"
    exit 1
fi

tar -xzvf $dir_name.tar.gz

cwd=$PWD
cd $cwd/$dir_name

grep -E "Patch[0-9]{4}:\s*[0-9]{4}-.*\.patch" $cwd/lxc.spec | awk '{print $2}' | while read line
do
    if [[ $line == '' || $line =~ ^\s*# ]]; then
        continue
    fi
    echo $cwd/$line
    patch -p1 -F1 -s < $cwd/$line
done

git init .
git add .
git config --local user.name "isuladci"
git config --local user.email "isulad@ci.com"
git commit -m "init repo"
git config --local --unset user.name
git config --local --unset user.email

cd $cwd
